name = "school-auth-bff"
main = "src/index.ts"
compatibility_date = "2026-05-18"

routes = [
	{ pattern = "superadmin.mutiurrahman.com/api/*", zone_name = "mutiurrahman.com" },
	{ pattern = "lbphs.gov.bd/api/*", zone_name = "lbphs.gov.bd" },
	{ pattern = "*.lbphs.gov.bd/api/*", zone_name = "lbphs.gov.bd" }
]

[vars]
BACKEND_URL = "https://apisms.mutiurrahman.com"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1
