packages:
  - client-next
  - dashboard
  - server
  - packages/*
  - workers/*
allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  workerd: true
