services:
  school_backend:
    build: .  
    image: school_backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - ${ENV_FILE:-".env"}
    networks:
      - school_network


networks:
  school_network:
    external: true
    name: ${school_name}_school_network
