services:
  school_backend:
    build: .  
    image: school_backend
    container_name: school_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - school_network
    env_file:
      - .env.prod

networks:
  school_network:
    driver: bridge
