services:
  school_backend:
    build: .  
    image: school_backend
    container_name: school_backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - school_network
    env_file:
      - .env.prod
    shm_size: '1g'


networks:
  school_network:
    driver: bridge
