services:
  postgres_school:
    image: postgres:17
    restart: unless-stopped     
    ports:
      - "${POSTGRES_PORT}:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - school_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}



volumes:
  db_data:
    name: postgres_school_${school_name}_data

networks:
  school_network:
    external: true
    name: ${school_name}_school_network
