services:
  school_redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - school_network

networks:
  school_network:
    external: true
    name: ${school_name}_school_network

volumes:
  redis_data:
    name: redis_school_${school_name}_data
