-- AlterTable
ALTER TABLE "marks" ALTER COLUMN "cq_marks" DROP NOT NULL,
ALTER COLUMN "cq_marks" DROP DEFAULT,
ALTER COLUMN "mcq_marks" DROP NOT NULL,
ALTER COLUMN "mcq_marks" DROP DEFAULT,
ALTER COLUMN "practical_marks" DROP NOT NULL,
ALTER COLUMN "practical_marks" DROP DEFAULT,
ALTER COLUMN "marks" DROP NOT NULL,
ALTER COLUMN "marks" DROP DEFAULT;
