import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Analytics } from "@/components/Analytics";
import { fetchSchoolConfig } from "@/queries/school.queries";
import fs from "fs";
import path from "path";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const school = await fetchSchoolConfig();
  const fontPath = path.join(process.cwd(), "app/fonts/Kalpurush-v0.258.woff2");
  const fontBase64 = fs.readFileSync(fontPath).toString("base64");

  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha512-Sfcb8v8pB+e+0f7FYq8VKcYfXnCrSW0a7HW0sXHUGbF6dU4mE0iQpQZbWq9T7yFR41x3SxgA2yZrO6wYkHfFvA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <style dangerouslySetInnerHTML={{
          __html: `
          @font-face {
            font-family: "Kalpurush";
            src: url("data:font/woff2;base64,${fontBase64}") format("woff2");
            font-weight: 100 900;
            font-display: block;
          }

          html, body {
            font-family: "Kalpurush", sans-serif;
          }
        `}} />
        <link rel="preload" href="/bg.png" as="image" fetchPriority="high" />
      </head>
      <body className="min-h-full flex flex-col">
        <Analytics measurementId={school?.gaMeasurementId} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
