import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";

const kalpurush = localFont({
  src: [{ path: "../public/fonts/Kalpurush-v0.258.woff2", weight: "100 900" }],
  display: "swap",
  preload: true,
});

// No manual <head> or <link> needed
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${kalpurush.className} h-full antialiased`}
    >
      <head>
        <link
          rel="preload"
          href="/bg.png"
          as="image"
          fetchPriority="high"
        />
        <link
          rel="preload"
          href="/fonts/Kalpurush-v0.258.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`min-h-full flex flex-col`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
